
== Customization ID


The {PEPPOL} Customization ID identifies the specification of content and rules that apply to the transaction. This BIS has required some minor additions and changes to the {CENBII} transaction. Following the {CENBII} methodology any extension must be communicated by adding an extension ID onto the Customization ID. The full syntax is:
----
<transactionId>:(restrictive|extended|partly):<extensionId>[(restrictive|extended|partly):<extensionId>].
----

Example:

[cols="20m,80"]
.CustomizationID
|===
|Transaction ID:
|`urn:www.cenbii.eu:transaction:biitrdm090:ver3.0`

|Extension ID:
|`urn:www.peppol.eu:bis:peppol54a:ver1.0`
|===


CustomizationID to use:

.For Submit tender:
----
urn:www.cenbii.eu:transaction:biitrdm090:ver3.0:extended:urn:www.peppol.eu:bis:peppol54a:ver1.0
----

.For Tender Receipt Notification:
----
urn:www.cenbii.eu:transaction:biitrdm045:ver3.0:extended:urn:www.peppol.eu:bis:peppol54a:ver1.0
----


.Example of usage:
[source, xml]
----
include::../{gendoc}/examples/Trdm090.xml[tags=custID]
----

IMPORTANT: Please note that CustomizationID element in the document instance MUST correspond to the Customization ID of the SMP Document Identifier.

<<<<
