

= Code lists and business rules

The piloting of {eSENS} for Submit Tender, is based on work done by {CENBII}, and business rules and code lists used are inherited from the follwing {CENBII} documents:

* UBL binding for Submit tender: CWA 17027-218
* UBL binding for Tender Reception Notification: CWA 17027-205
* Profile 54 Submit Tender: CWA 17027-119

IMPORTANT: The profile document and syntax implementation guides from {CENBII} must be considered when implementing Submit Tender based on this BIS document

In addition to the rules and code lists from the {CENBII} work, the {eSENS}  pilot is using {PEPPOL} Transport infrastructure, and some additional business rules has been added, to ensure correct use according to {PEPPOL} Policies. The testing/piloting has also revealed that there where a few other rules/code lists needed as validation artefacts to ensure an instance document is conformant with the {CENBII} specifications.

The following chapters gives an overview of any code lists and business rules added by the {eSENS} pilot project. For rules and code lists from {CENBII}, we refer to the published documents above.
